[package]
name = "mimalloc-ffi"
# match mimalloc version
version = "3.1.5"
edition = "2018"
rust-version = "1.56"
repository = "https://github.com/echohumm/memapi/tree/master/mimalloc"
license = "MIT OR Apache-2.0"
description = "FFI bindings for mimalloc"
build = "build.rs"
links = "mimalloc"
exclude = [
    "/c/bin",
    "/c/cmake",
    "/c/doc",
    "/c/docs",
    "/c/ide",
    "/c/test",
]

[dependencies]
libc = "^0.2"

[build-dependencies]
cc = "^1.0.94"

[features]
secure = []
debug = []
debug_in_debug = []
override = []
extended = []
arena = []
local_dynamic_tls = []
no_thp = []

[package.metadata.docs.rs]
features = ["extended"]